Repository lappis-unb/rasa-ptbr-boilerplate, pull requests merged in 2019-08, with the labels that each got.

#79 Update content Bot
  bot/e2e/e2e_stories.md
  coach/data/intents/aleatorio.md
  coach/data/intents/geral.md
  coach/data/stories/aleatorio.md
  coach/data/stories/geral.md
  coach/domain.yml
  coach/policy_config.yml
Labels: conteudo

#81 0.4.2
  README.md
  analytics/elasticsearch/export.json
  bot/e2e/e2e_stories.md
  coach/data/intents/aleatorio.md
  coach/data/intents/geral.md
  coach/data/stories/aleatorio.md
  coach/data/stories/geral.md
  coach/domain.yml
  coach/policy_config.yml
Labels: codigo/rasa, conteudo, evolucao

#63 Update rasa version to 1.2.2
  .gitignore
  Makefile
  bot/Makefile
  bot/connector.py
  bot/credentials.yml
  bot/run_rocketchat.py
  bot/test_stories.py
  bot/tracker_store.py
  coach/Makefile
  coach/core_config.yml
  coach/policy_config.yml
  coach/train.py
  docker-compose.yml
  docker/bot-rocketchat.env
  requirements.txt
Labels: codigo/rasa, evolucao
