Repository lappis-unb/rasa-ptbr-boilerplate, pull requests merged in 2020-10, with the labels that each got.

#178 Setup telegram
  README.md
  docs/setup_telegram.md
Labels: 📝 documentação

#181 Dockerizacao webchat
  Makefile
  docker-compose.yml
  modules/webchat/index.html
  modules/webchat/index.min.js
Labels: codigo/rasa, hacktoberfest-accepted

#183 Add rocketchat to boilerplate
  Makefile
  bot/Makefile
  bot/credentials.yml
  docker-compose.yml
  modules/rocketchat/bot_config.py
Labels: evolucao, hacktoberfest-accepted

#184 Improvements
  bot/actions/actions.py
  bot/actions/forms.py
  modules/analytics/setup_elastic.py
  modules/rabbitmq/consumer/consume_bot_messages.py
  modules/rocketchat/bot_config.py
Labels: :beer: Hacktoberfest, hacktoberfest-accepted, 🐛bug

#185 Organização de serviços
  Makefile
  bot/Makefile
  docker-compose.yml
  modules/webchat/index.html
Labels: :beer: Hacktoberfest, evolucao, hacktoberfest-accepted
